[default]
engine = "Llvm"
out = ["Lcov", "Json"]
output-dir = "coverage"
run-types = ["Tests", "Lib"]
exclude-files = ["target/*", "build.rs"]
timeout = "300"
all = true
branch = true
fail-under = 100.0
force-clean = true
